### ISSUE TITLE
Error: index out of bounds

### ISSUE THREAD

**Issue by PietroD** [califano-lab/ADVOCATE#1]
Hi,

When running `calCellTypeExpression` on own bulk data after predicting the fractions with `predict_bulk` I get `Error: index out of bounds`.

When testing with your pre-uploaded input data, the function returns no errors.

I have a matrix of bulk gene expression data with gene symbols as row names.

Thanks for the help

**Comment by laiseP** [comment]
Hi, thanks for reporting this issue. 
Maybe the problem can be the format of the input data.
Can you please double check  your input data using class() and str() functions?
You should see something like this:
> class(expmat)
[1] "matrix"
> str(expmat)
 num [1:14741, 1:120] -0.578 -0.257 -0.883 0.269 -1.038 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:14741] "61E3.4" "A1CF" "A2LD1" "A2M" ...
  ..$ : chr [1:120] "HSH15" "HSH17" "HSH13" "HSH1" ...
 - attr(*, "scaled:center")= Named num [1:120] 6.82 6.9 6.8 6.84 6.44 ...
  ..- attr(*, "names")= chr [1:120] "HSH15" "HSH17" "HSH13" "HSH1" ...
 - attr(*, "scaled:scale")= Named num [1:120] 1.65 1.56 1.66 1.62 1.88 ...
  ..- attr(*, "names")= chr [1:120] "HSH15" "HSH17" "HSH13" "HSH1" ...

Please let me know.
Thank you,
Pasquale

**Comment by PietroD** [comment]
Dear Pasquale,

Thanks for your answer.
Specifically, when I write "matrix of bulk gene expression data" I refer to the argument `bulkexp` in the `calCellTypeExpression` function.

When I type `str(bulkexp)` on your pre-uploaded data I get

> num [1:16357, 1:15] -1.141 -0.874 -0.603 -0.536 -0.211 ...
> - attr(*, "dimnames")=List of 2
  ..$ : chr [1:16357] "1/2-SBSRNA4" "61E3.4" "A1BG" "A1CF" ...
  ..$ : chr [1:15] "CUMC_012" "CUMC_013" "CUMC_064" "CUMC_066" ...

When I check the structure of my bulk data, replacing your `bulkexp`, I get

> num [1:54675, 1:39] 9.49 6.88 8.46 7.59 3.94 ...
> - attr(*, "dimnames")=List of 2
  ..$ : chr [1:54675] "DDR1" "RFC2" "HSPA6" "PAX8" ...
  ..$ : chr [1:39] "GSM388115" "GSM388116" "GSM388117" "GSM388118" ...

The output that you showed is from the `lcmexp` matrix but I am using yours so it has the same structure.

Thanks

**Comment by laiseP** [comment]
Hi Pietro, 
the input for the bulk  is really a simple matrix, that's why I automatically assumed  the problem was with the lcmexp matrix. Did you use the same matrix with the function "predict_bulk"?  if yes, and it worked  for "predict_bulk", I'd suggest to send us your file so we can double check.
Thank you,
Pasquale

**Comment by PietroD** [comment]
Dear Pasquale
Just realised that I had some NAs in the row names of my matrix.
Removing those solves the issue.
Thanks anyway
